// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, ttl
func (_m *MockSessionStore) Create(ctx context.Context, userID int64, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Duration) (string, error)); ok {
		return rf(ctx, userID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Duration) string); ok {
		r0 = rf(ctx, userID, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Duration) error); ok {
		r1 = rf(ctx, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - ttl time.Duration
func (_e *MockSessionStore_Expecter) Create(ctx interface{}, userID interface{}, ttl interface{}) *MockSessionStore_Create_Call {
	return &MockSessionStore_Create_Call{Call: _e.mock.On("Create", ctx, userID, ttl)}
}

func (_c *MockSessionStore_Create_Call) Run(run func(ctx context.Context, userID int64, ttl time.Duration)) *MockSessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_Create_Call) Return(sessionID string, err error) *MockSessionStore_Create_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *MockSessionStore_Create_Call) RunAndReturn(run func(context.Context, int64, time.Duration) (string, error)) *MockSessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionStore) Delete(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) Delete(ctx interface{}, sessionID interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionID)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return(_a0 error) *MockSessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionStore) GetUserID(ctx context.Context, sessionID string) (int64, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockSessionStore_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) GetUserID(ctx interface{}, sessionID interface{}) *MockSessionStore_GetUserID_Call {
	return &MockSessionStore_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx, sessionID)}
}

func (_c *MockSessionStore_GetUserID_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_GetUserID_Call) Return(_a0 int64, _a1 error) *MockSessionStore_GetUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_GetUserID_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockSessionStore_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
