// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletOwnershipChecker is an autogenerated mock type for the WalletOwnershipChecker type
type MockWalletOwnershipChecker struct {
	mock.Mock
}

type MockWalletOwnershipChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletOwnershipChecker) EXPECT() *MockWalletOwnershipChecker_Expecter {
	return &MockWalletOwnershipChecker_Expecter{mock: &_m.Mock}
}

// IsOwnedBy provides a mock function with given fields: ctx, walletID, userID
func (_m *MockWalletOwnershipChecker) IsOwnedBy(ctx context.Context, walletID int64, userID int64) error {
	ret := _m.Called(ctx, walletID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwnedBy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, walletID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletOwnershipChecker_IsOwnedBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwnedBy'
type MockWalletOwnershipChecker_IsOwnedBy_Call struct {
	*mock.Call
}

// IsOwnedBy is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID int64
//   - userID int64
func (_e *MockWalletOwnershipChecker_Expecter) IsOwnedBy(ctx interface{}, walletID interface{}, userID interface{}) *MockWalletOwnershipChecker_IsOwnedBy_Call {
	return &MockWalletOwnershipChecker_IsOwnedBy_Call{Call: _e.mock.On("IsOwnedBy", ctx, walletID, userID)}
}

func (_c *MockWalletOwnershipChecker_IsOwnedBy_Call) Run(run func(ctx context.Context, walletID int64, userID int64)) *MockWalletOwnershipChecker_IsOwnedBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockWalletOwnershipChecker_IsOwnedBy_Call) Return(_a0 error) *MockWalletOwnershipChecker_IsOwnedBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletOwnershipChecker_IsOwnedBy_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockWalletOwnershipChecker_IsOwnedBy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletOwnershipChecker creates a new instance of MockWalletOwnershipChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletOwnershipChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletOwnershipChecker {
	mock := &MockWalletOwnershipChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
