// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepository is an autogenerated mock type for the WalletRepository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) GetById(ctx context.Context, id int64) (domain.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockWalletRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockWalletRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockWalletRepository_GetById_Call {
	return &MockWalletRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockWalletRepository_GetById_Call) Run(run func(ctx context.Context, id int64)) *MockWalletRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletRepository_GetById_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletRepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetById_Call) RunAndReturn(run func(context.Context, int64) (domain.Wallet, error)) *MockWalletRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdForUpdate provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) GetByIdForUpdate(ctx context.Context, id int64) (domain.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdForUpdate")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetByIdForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdForUpdate'
type MockWalletRepository_GetByIdForUpdate_Call struct {
	*mock.Call
}

// GetByIdForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockWalletRepository_Expecter) GetByIdForUpdate(ctx interface{}, id interface{}) *MockWalletRepository_GetByIdForUpdate_Call {
	return &MockWalletRepository_GetByIdForUpdate_Call{Call: _e.mock.On("GetByIdForUpdate", ctx, id)}
}

func (_c *MockWalletRepository_GetByIdForUpdate_Call) Run(run func(ctx context.Context, id int64)) *MockWalletRepository_GetByIdForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletRepository_GetByIdForUpdate_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletRepository_GetByIdForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetByIdForUpdate_Call) RunAndReturn(run func(context.Context, int64) (domain.Wallet, error)) *MockWalletRepository_GetByIdForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockWalletRepository) Update(ctx context.Context, _a1 *domain.Wallet) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Wallet) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWalletRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Wallet
func (_e *MockWalletRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockWalletRepository_Update_Call {
	return &MockWalletRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockWalletRepository_Update_Call) Run(run func(ctx context.Context, _a1 *domain.Wallet)) *MockWalletRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Wallet))
	})
	return _c
}

func (_c *MockWalletRepository_Update_Call) Return(_a0 error) *MockWalletRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Wallet) error) *MockWalletRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
