// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	wallet "vault/internal/application/wallet"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionalResources is an autogenerated mock type for the TransactionalResources type
type MockTransactionalResources struct {
	mock.Mock
}

type MockTransactionalResources_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionalResources) EXPECT() *MockTransactionalResources_Expecter {
	return &MockTransactionalResources_Expecter{mock: &_m.Mock}
}

// TransactionRepository provides a mock function with no fields
func (_m *MockTransactionalResources) TransactionRepository() wallet.TransactionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TransactionRepository")
	}

	var r0 wallet.TransactionRepository
	if rf, ok := ret.Get(0).(func() wallet.TransactionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wallet.TransactionRepository)
		}
	}

	return r0
}

// MockTransactionalResources_TransactionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionRepository'
type MockTransactionalResources_TransactionRepository_Call struct {
	*mock.Call
}

// TransactionRepository is a helper method to define mock.On call
func (_e *MockTransactionalResources_Expecter) TransactionRepository() *MockTransactionalResources_TransactionRepository_Call {
	return &MockTransactionalResources_TransactionRepository_Call{Call: _e.mock.On("TransactionRepository")}
}

func (_c *MockTransactionalResources_TransactionRepository_Call) Run(run func()) *MockTransactionalResources_TransactionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionalResources_TransactionRepository_Call) Return(_a0 wallet.TransactionRepository) *MockTransactionalResources_TransactionRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalResources_TransactionRepository_Call) RunAndReturn(run func() wallet.TransactionRepository) *MockTransactionalResources_TransactionRepository_Call {
	_c.Call.Return(run)
	return _c
}

// WalletRepository provides a mock function with no fields
func (_m *MockTransactionalResources) WalletRepository() wallet.WalletRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WalletRepository")
	}

	var r0 wallet.WalletRepository
	if rf, ok := ret.Get(0).(func() wallet.WalletRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wallet.WalletRepository)
		}
	}

	return r0
}

// MockTransactionalResources_WalletRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletRepository'
type MockTransactionalResources_WalletRepository_Call struct {
	*mock.Call
}

// WalletRepository is a helper method to define mock.On call
func (_e *MockTransactionalResources_Expecter) WalletRepository() *MockTransactionalResources_WalletRepository_Call {
	return &MockTransactionalResources_WalletRepository_Call{Call: _e.mock.On("WalletRepository")}
}

func (_c *MockTransactionalResources_WalletRepository_Call) Run(run func()) *MockTransactionalResources_WalletRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionalResources_WalletRepository_Call) Return(_a0 wallet.WalletRepository) *MockTransactionalResources_WalletRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalResources_WalletRepository_Call) RunAndReturn(run func() wallet.WalletRepository) *MockTransactionalResources_WalletRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionalResources creates a new instance of MockTransactionalResources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionalResources(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionalResources {
	mock := &MockTransactionalResources{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
