// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletReader is an autogenerated mock type for the WalletReader type
type MockWalletReader struct {
	mock.Mock
}

type MockWalletReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletReader) EXPECT() *MockWalletReader_Expecter {
	return &MockWalletReader_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockWalletReader) Create(ctx context.Context, _a1 *domain.Wallet) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Wallet) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletReader_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWalletReader_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Wallet
func (_e *MockWalletReader_Expecter) Create(ctx interface{}, _a1 interface{}) *MockWalletReader_Create_Call {
	return &MockWalletReader_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockWalletReader_Create_Call) Run(run func(ctx context.Context, _a1 *domain.Wallet)) *MockWalletReader_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Wallet))
	})
	return _c
}

func (_c *MockWalletReader_Create_Call) Return(_a0 error) *MockWalletReader_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletReader_Create_Call) RunAndReturn(run func(context.Context, *domain.Wallet) error) *MockWalletReader_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockWalletReader) GetById(ctx context.Context, id int64) (domain.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletReader_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockWalletReader_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockWalletReader_Expecter) GetById(ctx interface{}, id interface{}) *MockWalletReader_GetById_Call {
	return &MockWalletReader_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockWalletReader_GetById_Call) Run(run func(ctx context.Context, id int64)) *MockWalletReader_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletReader_GetById_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletReader_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletReader_GetById_Call) RunAndReturn(run func(context.Context, int64) (domain.Wallet, error)) *MockWalletReader_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserId provides a mock function with given fields: ctx, userID
func (_m *MockWalletReader) GetByUserId(ctx context.Context, userID int64) (domain.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletReader_GetByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserId'
type MockWalletReader_GetByUserId_Call struct {
	*mock.Call
}

// GetByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockWalletReader_Expecter) GetByUserId(ctx interface{}, userID interface{}) *MockWalletReader_GetByUserId_Call {
	return &MockWalletReader_GetByUserId_Call{Call: _e.mock.On("GetByUserId", ctx, userID)}
}

func (_c *MockWalletReader_GetByUserId_Call) Run(run func(ctx context.Context, userID int64)) *MockWalletReader_GetByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletReader_GetByUserId_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletReader_GetByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletReader_GetByUserId_Call) RunAndReturn(run func(context.Context, int64) (domain.Wallet, error)) *MockWalletReader_GetByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletReader creates a new instance of MockWalletReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletReader {
	mock := &MockWalletReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
