// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	wallet "vault/internal/application/wallet"

	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// StartTransaction provides a mock function with given fields: ctx, caller
func (_m *MockUnitOfWork) StartTransaction(ctx context.Context, caller func(wallet.TransactionalResources) error) error {
	ret := _m.Called(ctx, caller)

	if len(ret) == 0 {
		panic("no return value specified for StartTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(wallet.TransactionalResources) error) error); ok {
		r0 = rf(ctx, caller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_StartTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTransaction'
type MockUnitOfWork_StartTransaction_Call struct {
	*mock.Call
}

// StartTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - caller func(wallet.TransactionalResources) error
func (_e *MockUnitOfWork_Expecter) StartTransaction(ctx interface{}, caller interface{}) *MockUnitOfWork_StartTransaction_Call {
	return &MockUnitOfWork_StartTransaction_Call{Call: _e.mock.On("StartTransaction", ctx, caller)}
}

func (_c *MockUnitOfWork_StartTransaction_Call) Run(run func(ctx context.Context, caller func(wallet.TransactionalResources) error)) *MockUnitOfWork_StartTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(wallet.TransactionalResources) error))
	})
	return _c
}

func (_c *MockUnitOfWork_StartTransaction_Call) Return(_a0 error) *MockUnitOfWork_StartTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_StartTransaction_Call) RunAndReturn(run func(context.Context, func(wallet.TransactionalResources) error) error) *MockUnitOfWork_StartTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
