// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"

	wallet "vault/internal/application/wallet"
)

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, command
func (_m *MockWalletService) Create(ctx context.Context, command wallet.CreateWalletCommand) (domain.Wallet, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.CreateWalletCommand) (domain.Wallet, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.CreateWalletCommand) domain.Wallet); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.CreateWalletCommand) error); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWalletService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - command wallet.CreateWalletCommand
func (_e *MockWalletService_Expecter) Create(ctx interface{}, command interface{}) *MockWalletService_Create_Call {
	return &MockWalletService_Create_Call{Call: _e.mock.On("Create", ctx, command)}
}

func (_c *MockWalletService_Create_Call) Run(run func(ctx context.Context, command wallet.CreateWalletCommand)) *MockWalletService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(wallet.CreateWalletCommand))
	})
	return _c
}

func (_c *MockWalletService_Create_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_Create_Call) RunAndReturn(run func(context.Context, wallet.CreateWalletCommand) (domain.Wallet, error)) *MockWalletService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id, userID
func (_m *MockWalletService) GetById(ctx context.Context, id int64, userID int64) (domain.Wallet, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (domain.Wallet, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) domain.Wallet); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(domain.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockWalletService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockWalletService_Expecter) GetById(ctx interface{}, id interface{}, userID interface{}) *MockWalletService_GetById_Call {
	return &MockWalletService_GetById_Call{Call: _e.mock.On("GetById", ctx, id, userID)}
}

func (_c *MockWalletService_GetById_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockWalletService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockWalletService_GetById_Call) Return(_a0 domain.Wallet, _a1 error) *MockWalletService_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetById_Call) RunAndReturn(run func(context.Context, int64, int64) (domain.Wallet, error)) *MockWalletService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
