// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"

	withdrawal "vault/internal/application/withdrawal"
)

// MockWithdrawalService is an autogenerated mock type for the WithdrawalService type
type MockWithdrawalService struct {
	mock.Mock
}

type MockWithdrawalService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdrawalService) EXPECT() *MockWithdrawalService_Expecter {
	return &MockWithdrawalService_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, command
func (_m *MockWithdrawalService) Do(ctx context.Context, command withdrawal.WithdrawalCommand) (domain.Transaction, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, withdrawal.WithdrawalCommand) (domain.Transaction, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, withdrawal.WithdrawalCommand) domain.Transaction); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, withdrawal.WithdrawalCommand) error); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawalService_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockWithdrawalService_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - command withdrawal.WithdrawalCommand
func (_e *MockWithdrawalService_Expecter) Do(ctx interface{}, command interface{}) *MockWithdrawalService_Do_Call {
	return &MockWithdrawalService_Do_Call{Call: _e.mock.On("Do", ctx, command)}
}

func (_c *MockWithdrawalService_Do_Call) Run(run func(ctx context.Context, command withdrawal.WithdrawalCommand)) *MockWithdrawalService_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(withdrawal.WithdrawalCommand))
	})
	return _c
}

func (_c *MockWithdrawalService_Do_Call) Return(_a0 domain.Transaction, _a1 error) *MockWithdrawalService_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawalService_Do_Call) RunAndReturn(run func(context.Context, withdrawal.WithdrawalCommand) (domain.Transaction, error)) *MockWithdrawalService_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdrawalService creates a new instance of MockWithdrawalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdrawalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdrawalService {
	mock := &MockWithdrawalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
