// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "vault/internal/application/auth"

	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, command
func (_m *MockAuthService) Login(ctx context.Context, command auth.LoginCommand) (auth.Session, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginCommand) (auth.Session, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginCommand) auth.Session); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Get(0).(auth.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.LoginCommand) error); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - command auth.LoginCommand
func (_e *MockAuthService_Expecter) Login(ctx interface{}, command interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, command)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, command auth.LoginCommand)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.LoginCommand))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 auth.Session, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, auth.LoginCommand) (auth.Session, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionID
func (_m *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, sessionID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function with given fields: ctx, sessionID
func (_m *MockAuthService) Me(ctx context.Context, sessionID string) (domain.User, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockAuthService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) Me(ctx interface{}, sessionID interface{}) *MockAuthService_Me_Call {
	return &MockAuthService_Me_Call{Call: _e.mock.On("Me", ctx, sessionID)}
}

func (_c *MockAuthService_Me_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Me_Call) Return(_a0 domain.User, _a1 error) *MockAuthService_Me_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Me_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *MockAuthService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, command
func (_m *MockAuthService) Register(ctx context.Context, command auth.RegisterCommand) error {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterCommand) error); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - command auth.RegisterCommand
func (_e *MockAuthService_Expecter) Register(ctx interface{}, command interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, command)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, command auth.RegisterCommand)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RegisterCommand))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, auth.RegisterCommand) error) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
