// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockWalletLocker is an autogenerated mock type for the WalletLocker type
type MockWalletLocker struct {
	mock.Mock
}

type MockWalletLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletLocker) EXPECT() *MockWalletLocker_Expecter {
	return &MockWalletLocker_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function with given fields: ctx, walletID, timeout
func (_m *MockWalletLocker) Lock(ctx context.Context, walletID int64, timeout time.Duration) (func(), error) {
	ret := _m.Called(ctx, walletID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 func()
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Duration) (func(), error)); ok {
		return rf(ctx, walletID, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Duration) func()); ok {
		r0 = rf(ctx, walletID, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Duration) error); ok {
		r1 = rf(ctx, walletID, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletLocker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockWalletLocker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID int64
//   - timeout time.Duration
func (_e *MockWalletLocker_Expecter) Lock(ctx interface{}, walletID interface{}, timeout interface{}) *MockWalletLocker_Lock_Call {
	return &MockWalletLocker_Lock_Call{Call: _e.mock.On("Lock", ctx, walletID, timeout)}
}

func (_c *MockWalletLocker_Lock_Call) Run(run func(ctx context.Context, walletID int64, timeout time.Duration)) *MockWalletLocker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockWalletLocker_Lock_Call) Return(_a0 func(), _a1 error) *MockWalletLocker_Lock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletLocker_Lock_Call) RunAndReturn(run func(context.Context, int64, time.Duration) (func(), error)) *MockWalletLocker_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletLocker creates a new instance of MockWalletLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletLocker {
	mock := &MockWalletLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
