// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "vault/internal/domain"

	mock "github.com/stretchr/testify/mock"

	transaction "vault/internal/application/transaction"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: ctx, id, command
func (_m *MockTransactionService) GetById(ctx context.Context, id int64, command transaction.GetTransactionByIdCommand) (domain.Transaction, error) {
	ret := _m.Called(ctx, id, command)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, transaction.GetTransactionByIdCommand) (domain.Transaction, error)); ok {
		return rf(ctx, id, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, transaction.GetTransactionByIdCommand) domain.Transaction); ok {
		r0 = rf(ctx, id, command)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, transaction.GetTransactionByIdCommand) error); ok {
		r1 = rf(ctx, id, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockTransactionService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - command transaction.GetTransactionByIdCommand
func (_e *MockTransactionService_Expecter) GetById(ctx interface{}, id interface{}, command interface{}) *MockTransactionService_GetById_Call {
	return &MockTransactionService_GetById_Call{Call: _e.mock.On("GetById", ctx, id, command)}
}

func (_c *MockTransactionService_GetById_Call) Run(run func(ctx context.Context, id int64, command transaction.GetTransactionByIdCommand)) *MockTransactionService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(transaction.GetTransactionByIdCommand))
	})
	return _c
}

func (_c *MockTransactionService_GetById_Call) Return(_a0 domain.Transaction, _a1 error) *MockTransactionService_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetById_Call) RunAndReturn(run func(context.Context, int64, transaction.GetTransactionByIdCommand) (domain.Transaction, error)) *MockTransactionService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, command
func (_m *MockTransactionService) List(ctx context.Context, command transaction.ListTransactionsCommand) ([]domain.Transaction, int64, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListTransactionsCommand) ([]domain.Transaction, int64, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.ListTransactionsCommand) []domain.Transaction); ok {
		r0 = rf(ctx, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transaction.ListTransactionsCommand) int64); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, transaction.ListTransactionsCommand) error); ok {
		r2 = rf(ctx, command)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - command transaction.ListTransactionsCommand
func (_e *MockTransactionService_Expecter) List(ctx interface{}, command interface{}) *MockTransactionService_List_Call {
	return &MockTransactionService_List_Call{Call: _e.mock.On("List", ctx, command)}
}

func (_c *MockTransactionService_List_Call) Run(run func(ctx context.Context, command transaction.ListTransactionsCommand)) *MockTransactionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(transaction.ListTransactionsCommand))
	})
	return _c
}

func (_c *MockTransactionService_List_Call) Return(_a0 []domain.Transaction, _a1 int64, _a2 error) *MockTransactionService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransactionService_List_Call) RunAndReturn(run func(context.Context, transaction.ListTransactionsCommand) ([]domain.Transaction, int64, error)) *MockTransactionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
